### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by prestonvanloon** [goerli/schlesi#1]
Hi, I'm from the @prysmaticlabs team. We have recently launched our latest testnet ([Topaz](https://medium.com/prysmatic-labs/introducing-topaz-testnet-8e8a4e00a700)) on the v0.11.1 spec version with full mainnet configuration. We are wondering how we can contribute to the multiclient testnet effort. 

Should we add Topaz information here? It is multi-client compatible.

I see Teku specific information v0.11.1, but using fractional deposits. Is the scope of _The Multiclient Testnet_ defined? Are we planning to use the exact configuration intended for mainnet?

Thanks

**Comment by q9f** [comment]
Thanks. So, the scope is defined in the Readme, basically trying to get as close to mainnet condition as possible. The full 32 ETH deposit thing is something I had planned to do as one of the final steps. For now, I believe fractional deposits are sufficient. But I applaud the Topaz testnet for moving closer to mainnet.

Back then, for the 0.10 spec, I was using Lighthouse and Teku to understand how setting up beacon chain testnets works. At that time, the 0.10-spec version of Prysm no longer worked for me, so it didn't make it into the first iteration of Schlesi.

Now, for the 0.11 spec, the clients are still implementing the protocol at different pace. The spec you see is a Teku-based network which had some Lighthouse validators attached but it didn't work out as Teku wouldn't pick up the spec and Lighthouse went on progressing the chain without Teku. I'm still investigating that.

So my next step, and therefore your timing is perfect, is trying to just test networking and synchronization without any validator clients. I wanted to see how far I would getting adding Ligthouse and Teku and maybe other nodes to the Topaz testnet. Danny would call that "multi-client" play, the ultimate goal would be proove baseline compatibility between the clients without breaking your testnet :)

I see you added your Topaz config to https://github.com/eth2-clients/eth2-testnets/tree/master/prysm/Topaz(v0.11.1) - that's probably enough for now. I will try working towards adding clients to Topaz just to get a sense how far each client progresses so far and would raise issues I discover with the associated teams. Lighthouse will also launch a new public testnet soon, so that would also be interesting to play around with.

For more substantial multi-client efforts, i.e., another iteration of Schlesi, we would opt for smaller semi-public testnets because the chance to break them is much higher. For now, the best contribution from you and other core developers to patiently answer my questions and pointing me out to the best/stable version of your implementation.

There's a Schlesi Gitter for contributors: https://gitter.im/goerli/schlesi/

But I'm also on Discord, either using the #testnet channel on the ETH2 Discord or talking to the teams individually. Let me know if you have any further questions and thanks for reaching out!

**Comment by prestonvanloon** [comment]
Thanks for the detailed response! On the Prysm side of things, Topaz has a consensus breaking bug https://github.com/prysmaticlabs/prysm/pull/5595. Our plan is to bundle this with the Topaz planned restart for v0.12. With that said, is v0.12 going to the long running schlesi multi-client testnet before mainnet?

I'll close this issue for now since you've answered my original question. Thanks!

**Comment by q9f** [comment]
> With that said, is v0.12 going to the long running schlesi multi-client testnet before mainnet?

That's hard to say currently. I managed to setup a local testnet between Prysm and Lighthouse today using your v0.12 branch with the patch. It would be nice if we could have some 0.11 compatibility on that branch for a while, so other clients can catch up, e.g., Teku.

I would like to spin up a v0.11 version of Schlesi first. I will probably use Prysm to bootstrap it, add Lighthouse to it and then see which other clients are ready to join the network. This would probably one of the mid-term, fail-fast testnets. 0.12 is currently too far away.
